### PR TITLE
Remove `/requirements.txt`, update optional dependencies recommendation

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by ak-gupta** [comment]
Hm, waht's the rationale behind this? We typically refresh and use the `requirements.txt` to help us create a stable dev environment (especially for CI/CD). Historically, it's been very useful on other projects when debugging issues.

**Comment by kuraga** [comment]
Ok, understand. I agree to update.

But [which option](https://github.com/lazyscribe/lazyscribe/blob/5ed018be81b22818c230457016e29c66d5fc8448/pyproject.toml#L26) `/requirements.txt` stand for?

**Comment by ak-gupta** [comment]
In other projects I've used `uv` with the `dev` optional dependency to compile a `dev-requirements.txt` file. We can do that here as well

**Comment by kuraga** [comment]
> We typically refresh and use the `requirements.txt` to help us create a stable dev environment (especially for CI/CD).

Isn't it a [constraints file](https://pip.pypa.io/en/stable/user_guide/#constraints-files) instead?
Then, we should put there _every_ possible dependency.

**Comment by ak-gupta** [comment]
It uses the requirements syntax, although I've never used a constraints file specifically -- `uv` specifies both direct and transient dependencies when you call `uv pip compile`, so it goes through the whole tree

**Comment by kuraga** [comment]
Ok, thanks!

I said not about `uv` but just `pip install`. 

`-r` and `-e` (both) turn on a union AFAIK. `-c` and `-e` (both) turn on the list from `setup.py` AFAIK (with constraints from `-c`).

So, the question about the option is actual...

P.S. This PR's addition of `[test]` is incorrect. `[dev]` already intendes `[test]`.

**Pull request closed without merging**
