### PR TITLE
New `__str__` representation

### PR DESCRIPTION
**Pull request by kuraga**
See https://github.com/lazyscribe/lazyscribe/issues/28, p. 7.

### CODE REVIEW

**Comment by kuraga** [comment]
```
lazyscribe/experiment.py:428 in public method `__str__`:
        D105: Missing docstring in magic method
lazyscribe/test.py:33 in public method `__str__`:
        D105: Missing docstring in magic method
lazyscribe/test.py:55 in public method `__str__`:
        D[10](https://github.com/lazyscribe/lazyscribe/actions/runs/8308784410/job/22739390565?pr=37#step:6:11)5: Missing docstring in magic method
```

Should I add a magic comment?

**Comment by ak-gupta** [comment]
Yeah, can you add a docstring? Could be as simple as

```
"""String representation."""
```

**Comment by kuraga** [comment]
Oh, sure.

**Comment by kuraga** [comment]
```
        D401: First line should be in imperative mood; try rephrasing (found 'String')
```

:slightly_smiling_face:

**Comment by ak-gupta** [comment]
Closing in favour of #64

**Pull request closed without merging**
