### PR TITLE
Implement `Test.log_parameter` (closes #44)

### LINKED ISSUE #44: [Proposition]  Metadata for experiments and tests
Continuation of #28 , p. 6.

**Idea:** to introduce _metadata_ (string-keyed any-valued dictionary) for _experiments_ and _tests_.

1. The `Experiment`'s constructor should have the `metadata: dict[str, any]` argument.
It is stored in the object, say `experiment`.
2. There is the `experiment.metadata` attribute.
3. There is a way to mutate `.metadata`.
Maybe, the `experiment.add_metadata(name: str, value: any)` method.
4. The same for `Test`s.
5. Integrate the `.name`, `.description`, etc. into the `.metadata`?

---

Reminder that it's not something new: we already have the metadata, `.name` and `.description`.

---

> What is the distinction is between `parameters` and `metadata` in this case?

1. Tests don't have `parameters`.
2. See "The second example" -> "Secondly, ...".

---

**The first example:** there are _tests_ (and, keep in mind, _experiments_) of different _types_ on the task. A test of each _type_ has different set of metrics, etc. The test's `.type` is neither a metric nor a parameter but a _metadata_. Exactly the same, the test's `.name` and `.description` are such _metadata_.

---

**The second example (continuation of the first):** during the network training, I have different tests.

Firstly, they are different types (see above): multiple tests _during_ the epoch, and more full validation _after_ the epoch. These types of tests have different _set_ of metrics, it would be conveniently to be able to _filter_ each of them. Now I'm filtering using the `.description` or available metric names.

Secondly, each test in these scheme has a real _metadata_: _number of epoch_ it was evaluated at. The `.epoch` is neither a metric nor a parameter but a _metadata_. Now I'm storing it in the `.description`, too.

---

#43 adds kind of such _metadata_: the _tags_ for experiments: `experiment.tags: list[str]`.

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Review by ak-gupta — COMMENTED** [review]
Code generally looks good to me. Can you resolve the `ruff` errors? Any thoughts @jdawang

**Comment by kuraga** [comment]
@ak-gupta, done.

**Comment by jdawang** [comment]
I think codecov is rate limiting us which is why the GH workflows are failing. Probably should get an alternative. Code looks good to me.

**Review by ak-gupta — APPROVED** [review]

**Comment by kuraga** [comment]
Thanks!

**Pull request merged**
