### PR TITLE
Bumping the version and removing a file

### PR DESCRIPTION
**Pull request by ak-gupta**
## Description

In this PR I've bumped the version and removed the `sg_execution_times.rst` file.

### CODE REVIEW

**Comment by kuraga** [comment]
#37 ?

**Comment by kuraga** [comment]
Also, https://github.com/lazyscribe/lazyscribe/issues/44#issuecomment-2115623319 .

**Comment by ak-gupta** [comment]
Our releases are cut from `main`, so this is just preparation

**Comment by ak-gupta** [comment]
> #37 ?

Yeah, sorry I saw that. This PR also removes that file.

**Comment by ak-gupta** [comment]
> Also, [#44 (comment)](https://github.com/lazyscribe/lazyscribe/issues/44#issuecomment-2115623319) .

Let's bump that feature to the next release so we can get some of the features we've already built deployed to PyPI.

**Comment by kuraga** [comment]
> Let's bump that feature to the next release so we can get some of the features we've already built deployed to PyPI.

Ok.

**Pull request merged**
