### PR TITLE
docs: string representation for experiment and test modules

### LINKED ISSUE #50: Documentation issues
1. https://lazyscribe.github.io/ hasn't been rebuilt ([reference](https://lazyscribe.github.io/lazyscribe/api/lazyscribe.html#lazyscribe.project.Project.to_tabular)).
2. https://lazyscribe.github.io/ has `Copyright © 2021`.
3. https://lazyscribe.readthedocs.io/ still exists itself. Should we remove it or update somehow?

P.S.
4. Could https://lazyscribe.github.io/ have version switcher?

### LINKED ISSUE #52: Badge links are invalid
Badge links are invalid in `/README.md`.

### PR DESCRIPTION
**Pull request by ak-gupta**
## Description

Duplicate of #37.

Fixes #50 
Fixes #52 
Addresses p. 24 from #28

### CODE REVIEW

**Review by gladysteh99 — APPROVED** [review]
LGTM!

**Comment by kuraga** [comment]
https://github.com/lazyscribe/lazyscribe/issues/52#issuecomment-2436450632

**Comment by kuraga** [comment]
[p.24](https://github.com/lazyscribe/lazyscribe/issues/28#issuecomment-2317661538) from #28 is addressed partially only - `Project.append` documentation is untouched.

**Comment by kuraga** [comment]
Thanks very much!

#52 is fixed partially only - see https://github.com/lazyscribe/lazyscribe/issues/52#issuecomment-2436450632.

[p.24](https://github.com/lazyscribe/lazyscribe/issues/28#issuecomment-2317661538) from #28 is addressed partially only - `Project.append` documentation is untouched.

**Pull request merged**
